"""Exports of the event outputs as CSV text and a PDF report (AISpec.md section 5.4a).

Flask-free functions built on `h2h.outputs`, so every export is as live as the pages
(recomputed on each call) and counts only completed passes. Each carries the date and time
it was made (Feedback 6) and both the starting and the to-date handicap of every archer. CSV
is plain UTF-8 with a header row (no byte-order mark, so `pandas.read_csv` gets clean column
names); the PDF is A4 with plain tables, generated by `fpdf2` using its built-in Helvetica font.
"""

from __future__ import annotations

import csv
import io
from datetime import datetime
from typing import TYPE_CHECKING

from .models import Event
from .outputs import archer_results, leaderboard

if TYPE_CHECKING:
    from fpdf import FPDF

LEADERBOARD_HEADER = [
    "Rank",
    "Archer",
    "Points",
    "Passes decided",
    "Starting handicap",
    "To-date handicap",
    "Exported",
]
ARCHER_RESULTS_HEADER = [
    "Archer",
    "Starting handicap",
    "To-date handicap",
    "Pass",
    "Opponent",
    "Score",
    "Percentile (%)",
    "Handicap of score",
    "Exported",
]
LEADERBOARD_PDF_HEADER = [
    "Rank",
    "Archer",
    "Points",
    "Passes decided",
    "Starting handicap",
    "To-date handicap",
]
RESULT_COLUMNS = ["Pass", "Opponent", "Score", "Percentile", "Handicap"]
PASS_START = "Pass starting handicap"  # the extra column shown only when handicaps are updated


def timestamp_text(now: datetime) -> str:
    """The export time as shown inside a file: "2026-10-04 15:30:12" (local time, to the second)."""
    return now.strftime("%Y-%m-%d %H:%M:%S")


def filename_stamp(now: datetime) -> str:
    """The export time as used in a file name: "20261004-153012"."""
    return now.strftime("%Y%m%d-%H%M%S")


def _percent(fraction: float) -> str:
    """A 0-1 fraction as a percentage to one decimal place, without the sign (0.598 -> "59.8")."""
    return f"{fraction * 100:.1f}"


def _handicap_text(handicap: float | None) -> str:
    """A handicap implied by a score to one decimal place, or "-" if it has none."""
    return "-" if handicap is None else f"{handicap:.1f}"


def _csv_to_date(handicap: float | None) -> str:
    """A to-date handicap for a CSV cell: one decimal place, or empty if there is none."""
    return "" if handicap is None else f"{handicap:.1f}"


def _csv_text(header: list[str], rows: list[list[object]]) -> str:
    """Write a header and rows as CSV text with standard quoting.

    Parameters
    ----------
    header : list[str]
        The column names.
    rows : list[list[object]]
        The data rows; each cell is written with `str` (so a number stays a plain number).

    Returns
    -------
    str
        The CSV, rows ending in CRLF as the csv module writes them.
    """
    buffer = io.StringIO()
    writer = csv.writer(buffer)
    writer.writerow(header)
    writer.writerows(rows)
    return buffer.getvalue()


def leaderboard_csv(event: Event, now: datetime | None = None) -> str:
    """The leaderboard as CSV.

    Columns: `Rank,Archer,Points,Passes decided,Starting handicap,To-date handicap,Exported`.
    The starting handicap is the one entered; the to-date handicap is to one decimal place
    (empty if the archer has none yet); `Exported` is the time of the export on every row.

    Parameters
    ----------
    event : h2h.models.Event
        The event.
    now : datetime.datetime | None, default=None
        The export time; defaults to the current local time.

    Returns
    -------
    str
        CSV text with one row per archer, in rank order, over the completed passes.
    """
    stamp = timestamp_text(now or datetime.now())
    rows = [
        [
            r.rank,
            r.name,
            r.points,
            r.passes_decided,
            f"{r.starting_handicap:g}",
            _csv_to_date(r.to_date_handicap),
            stamp,
        ]
        for r in leaderboard(event)
    ]
    return _csv_text(LEADERBOARD_HEADER, rows)


def archer_results_csv(event: Event, now: datetime | None = None) -> str:
    """Every archer's results as one tidy CSV table (no Average rows).

    Columns: `Archer,Starting handicap,To-date handicap,Pass,Opponent,Score,Percentile (%),
    [Pass starting handicap,]Handicap of score,Exported`, one row per archer per completed
    pass; `Pass starting handicap` (the handicap that pass's distribution was built from, one
    decimal place) is present only when the event updates handicaps. The two handicap
    columns repeat the archer's values on each of their rows (the to-date one is empty if they
    have none); the percentile is a plain number such as 59.8; a score of 0, which has no
    implied handicap, leaves `Handicap of score` empty; `Exported` is the export time.

    Parameters
    ----------
    event : h2h.models.Event
        The event.
    now : datetime.datetime | None, default=None
        The export time; defaults to the current local time.

    Returns
    -------
    str
        CSV text; just the header if no pass is completed yet.
    """
    stamp = timestamp_text(now or datetime.now())
    updating = event.update_handicaps
    header = list(ARCHER_RESULTS_HEADER)
    if updating:
        header.insert(header.index("Handicap of score"), PASS_START)
    rows = []
    for section in archer_results(event):
        for row in section.rows:
            cells = [
                section.name,
                f"{section.handicap:g}",
                _csv_to_date(section.to_date_handicap),
                row.pass_number,
                row.opponent,
                row.score,
                _percent(row.percentile),
            ]
            if updating:
                cells.append(f"{row.start_handicap:.1f}")
            cells.extend(["" if row.handicap is None else f"{row.handicap:.1f}", stamp])
            rows.append(cells)
    return _csv_text(header, rows)


def _latin1(text: str) -> str:
    """Make text safe for the PDF's built-in font, which covers Latin-1 only.

    Other characters become "?" (AISpec.md Assumption 39).
    """
    return text.encode("latin-1", "replace").decode("latin-1")


def _add_table(pdf: FPDF, header: list[str], rows: list[list[str]], average: list | None = None) -> None:
    """Draw a plain table (headings repeat on a new page, rows are never split).

    Parameters
    ----------
    pdf : fpdf.FPDF
        The document being written.
    header : list[str]
        The column headings.
    rows : list[list[str]]
        The body rows, one string per column.
    average : list | None, default=None
        Optional last row as `[label, *remaining cells]`, where the label spans the
        first two columns (Pass and Opponent) of a results table.
    """
    with pdf.table(text_align="LEFT", line_height=6) as table:
        heading = table.row()
        for name in header:
            heading.cell(_latin1(name))
        for cells in rows:
            row = table.row()
            for cell in cells:
                row.cell(_latin1(cell))
        if average is not None:
            row = table.row()
            row.cell(_latin1(average[0]), colspan=2)
            for cell in average[1:]:
                row.cell(_latin1(cell))


def results_pdf(event: Event, now: datetime | None = None) -> bytes:
    """The whole report as an A4 PDF: title, leaderboard, then each archer's results.

    Parameters
    ----------
    event : h2h.models.Event
        The event.
    now : datetime.datetime | None, default=None
        The export time shown under the title; defaults to the current local time.

    Returns
    -------
    bytes
        The PDF file. The title block says when it was exported and how many of the event's
        passes are completed; the leaderboard and each archer's heading carry the starting and
        to-date handicap; each archer has a table with an Average row, as on the Archer results
        page.

    Notes
    -----
    `fpdf2` is imported on the first call rather than with this module.
    """
    # Imported here, not at the top, so the browser engine can install fpdf2 (with pillow and
    # fonttools, about 2.5 MB) only when the first PDF is requested (decision D16).
    from fpdf import FPDF

    stamp = timestamp_text(now or datetime.now())
    pdf = FPDF(orientation="P", unit="mm", format="A4")
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.set_title("Handicapped H2H results")
    pdf.add_page()

    completed = len(event.completed_passes)
    pdf.set_font("Helvetica", "B", 16)
    pdf.cell(0, 10, "Handicapped H2H results", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(0, 5, f"Exported {stamp} (local time)", new_x="LMARGIN", new_y="NEXT")
    pdf.multi_cell(
        0,
        5,
        f"{len(event.archers)} archers, {event.n_pass} arrows per pass. {completed} of "
        f"{len(event.schedule)} passes completed (only completed passes are counted).",
        new_x="LMARGIN",
        new_y="NEXT",
    )
    pdf.ln(3)

    pdf.set_font("Helvetica", "B", 13)
    pdf.cell(0, 8, "Leaderboard", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)
    _add_table(
        pdf,
        LEADERBOARD_PDF_HEADER,
        [
            [
                str(r.rank),
                r.name,
                str(r.points),
                str(r.passes_decided),
                f"{r.starting_handicap:g}",
                _handicap_text(r.to_date_handicap),
            ]
            for r in leaderboard(event)
        ],
    )

    for section in archer_results(event):
        if pdf.get_y() > pdf.h - 55:
            pdf.add_page()  # keep a heading together with the start of its table
        pdf.ln(4)
        pdf.set_font("Helvetica", "B", 12)
        pdf.cell(
            0,
            8,
            _latin1(
                f"{section.name} - total score {section.total_score} - starting handicap "
                f"{section.handicap:g} - to-date handicap {_handicap_text(section.to_date_handicap)}"
            ),
            new_x="LMARGIN",
            new_y="NEXT",
        )
        pdf.set_font("Helvetica", "", 10)
        if not section.rows:
            pdf.cell(0, 6, "No completed pass yet.", new_x="LMARGIN", new_y="NEXT")
            continue
        average = section.averages
        updating = event.update_handicaps
        columns = list(RESULT_COLUMNS)
        body = []
        for row in section.rows:
            cells = [str(row.pass_number), row.opponent, str(row.score), f"{_percent(row.percentile)}%"]
            if updating:
                cells.append(f"{row.start_handicap:.1f}")
            cells.append(_handicap_text(row.handicap))
            body.append(cells)
        average_cells = ["Average", f"{average.score:.1f}", f"{_percent(average.percentile)}%"]
        if updating:
            columns.insert(columns.index("Handicap"), PASS_START)
            average_cells.append(f"{average.start_handicap:.1f}")
        average_cells.append(_handicap_text(average.handicap))
        _add_table(pdf, columns, body, average=average_cells)
    return bytes(pdf.output())
