"""Exports of the event outputs as CSV text and a PDF report (AISpec.md section 5.4a).

Flask-free functions built on `h2h.outputs`, so every export is as live as the pages
(recomputed on each call) and counts only completed passes. CSV is plain UTF-8 with a
header row (no byte-order mark, so `pandas.read_csv` gets clean column names); the PDF
is A4 with plain tables, generated by `fpdf2` using its built-in Helvetica font.
"""

from __future__ import annotations

import csv
import io

from fpdf import FPDF

from .models import Event
from .outputs import archer_results, leaderboard

LEADERBOARD_HEADER = ["Rank", "Archer", "Points", "Passes decided"]
ARCHER_RESULTS_HEADER = [
    "Archer",
    "Handicap",
    "Pass",
    "Opponent",
    "Score",
    "Percentile (%)",
    "Handicap of score",
]
RESULT_COLUMNS = ["Pass", "Opponent", "Score", "Percentile", "Handicap"]


def _percent(fraction: float) -> str:
    """A 0-1 fraction as a percentage to one decimal place, without the sign (0.598 -> "59.8")."""
    return f"{fraction * 100:.1f}"


def _handicap_text(handicap: float | None) -> str:
    """A handicap implied by a score to one decimal place, or "-" if it has none."""
    return "-" if handicap is None else f"{handicap:.1f}"


def _csv_text(header: list[str], rows: list[list[object]]) -> str:
    """Write a header and rows as CSV text with standard quoting.

    Parameters
    ----------
    header : list[str]
        The column names.
    rows : list[list[object]]
        The data rows; each cell is written with `str` (so a number stays a plain number).

    Returns
    -------
    str
        The CSV, rows ending in CRLF as the csv module writes them.
    """
    buffer = io.StringIO()
    writer = csv.writer(buffer)
    writer.writerow(header)
    writer.writerows(rows)
    return buffer.getvalue()


def leaderboard_csv(event: Event) -> str:
    """The leaderboard as CSV: `Rank,Archer,Points,Passes decided`.

    Parameters
    ----------
    event : h2h.models.Event
        The event.

    Returns
    -------
    str
        CSV text with one row per archer, in rank order, over the completed passes.
    """
    rows = [[r.rank, r.name, r.points, r.passes_decided] for r in leaderboard(event)]
    return _csv_text(LEADERBOARD_HEADER, rows)


def archer_results_csv(event: Event) -> str:
    """Every archer's results as one tidy CSV table (no Average rows).

    Columns: `Archer,Handicap,Pass,Opponent,Score,Percentile (%),Handicap of score`, one
    row per archer per completed pass. `Handicap` is the one entered at Stage 2; the
    percentile is a plain number such as 59.8; a score of 0, which has no implied
    handicap, leaves `Handicap of score` empty.

    Parameters
    ----------
    event : h2h.models.Event
        The event.

    Returns
    -------
    str
        CSV text; just the header if no pass is completed yet.
    """
    rows = []
    for section in archer_results(event):
        for row in section.rows:
            rows.append(
                [
                    section.name,
                    f"{section.handicap:g}",
                    row.pass_number,
                    row.opponent,
                    row.score,
                    _percent(row.percentile),
                    "" if row.handicap is None else f"{row.handicap:.1f}",
                ]
            )
    return _csv_text(ARCHER_RESULTS_HEADER, rows)


def _latin1(text: str) -> str:
    """Make text safe for the PDF's built-in font, which covers Latin-1 only.

    Other characters become "?" (AISpec.md Assumption 39).
    """
    return text.encode("latin-1", "replace").decode("latin-1")


def _add_table(pdf: FPDF, header: list[str], rows: list[list[str]], average: list | None = None) -> None:
    """Draw a plain table (headings repeat on a new page, rows are never split).

    Parameters
    ----------
    pdf : fpdf.FPDF
        The document being written.
    header : list[str]
        The column headings.
    rows : list[list[str]]
        The body rows, one string per column.
    average : list | None, default=None
        Optional last row as `[label, *remaining cells]`, where the label spans the
        first two columns (Pass and Opponent) of a results table.
    """
    with pdf.table(text_align="LEFT", line_height=6) as table:
        heading = table.row()
        for name in header:
            heading.cell(_latin1(name))
        for cells in rows:
            row = table.row()
            for cell in cells:
                row.cell(_latin1(cell))
        if average is not None:
            row = table.row()
            row.cell(_latin1(average[0]), colspan=2)
            for cell in average[1:]:
                row.cell(_latin1(cell))


def results_pdf(event: Event) -> bytes:
    """The whole report as an A4 PDF: title, leaderboard, then each archer's results.

    Parameters
    ----------
    event : h2h.models.Event
        The event.

    Returns
    -------
    bytes
        The PDF file. The title says how many of the event's passes are completed;
        each archer has a heading (name, total score, handicap) and a table with an
        Average row, as on the Archer results page.
    """
    pdf = FPDF(orientation="P", unit="mm", format="A4")
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.set_title("Handicapped H2H results")
    pdf.add_page()

    completed = len(event.completed_passes)
    pdf.set_font("Helvetica", "B", 16)
    pdf.cell(0, 10, "Handicapped H2H results", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)
    pdf.multi_cell(
        0,
        5,
        f"{len(event.archers)} archers, {event.n_pass} arrows per pass. {completed} of "
        f"{len(event.schedule)} passes completed (only completed passes are counted).",
        new_x="LMARGIN",
        new_y="NEXT",
    )
    pdf.ln(3)

    pdf.set_font("Helvetica", "B", 13)
    pdf.cell(0, 8, "Leaderboard", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)
    _add_table(
        pdf,
        LEADERBOARD_HEADER,
        [[str(r.rank), r.name, str(r.points), str(r.passes_decided)] for r in leaderboard(event)],
    )

    for section in archer_results(event):
        if pdf.get_y() > pdf.h - 55:
            pdf.add_page()  # keep a heading together with the start of its table
        pdf.ln(4)
        pdf.set_font("Helvetica", "B", 12)
        pdf.cell(
            0,
            8,
            _latin1(f"{section.name} - total score {section.total_score} - handicap {section.handicap:g}"),
            new_x="LMARGIN",
            new_y="NEXT",
        )
        pdf.set_font("Helvetica", "", 10)
        if not section.rows:
            pdf.cell(0, 6, "No completed pass yet.", new_x="LMARGIN", new_y="NEXT")
            continue
        average = section.averages
        _add_table(
            pdf,
            RESULT_COLUMNS,
            [
                [
                    str(row.pass_number),
                    row.opponent,
                    str(row.score),
                    f"{_percent(row.percentile)}%",
                    _handicap_text(row.handicap),
                ]
                for row in section.rows
            ],
            average=[
                "Average",
                f"{average.score:.1f}",
                f"{_percent(average.percentile)}%",
                _handicap_text(average.handicap),
            ],
        )
    return bytes(pdf.output())
